<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param \Datetime $date
     * @param $token
     * @return mixed
     * @throws
     */
    public function tokenIsValid($token)
    {
        $date = new \DateTime('NOW -20 minutes', new \DateTimezone("Europe/Paris"));

        return $this->createQueryBuilder('a')
            ->where('a.dateToken >= :date')
            ->andWhere('a.token = :token')
            ->setParameter('date', $date)
            ->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
